name: AuthorizeApp GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      id: Ngh
      uses: JamesIves/github-pages-deploy-action@master
      env:
       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       BRANCH: gh-pages
       FOLDER: dist/authorize-example
       BUILD_SCRIPT: npm install && npm test && npm run e2e &&npx ng build --prod --base-href https://chou-ting-hsiao.github.io/AuthorizeApp/

    - name: Notify
      id: Notify
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: ${{ format('{0} {1} \n {2}', github.workflow,  job.status, 'https://chou-ting-hsiao.github.io/AuthorizeApp/')}}
