name: AuthorizeApp GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  environment-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: Checkout
      uses: actions/checkout@master

    - name: Use Node.js 12.8
      id: Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8

    - name: install
      id: install
      run: npm install

  Lint:
    runs-on: ubuntu-latest
    steps:

    - name: Lint
      id: Lint
      run: npx ng lint

    needs: environment-build

  test:
    runs-on: ubuntu-latest
    steps:

    - name: test
      id: test
      run: npm test

    needs: environment-build
  
  e2e:
    runs-on: ubuntu-latest
    steps:

    - name: update chrome
      id: update
      run: npx webdriver-manager clean && npx webdriver-manager update --versions.chrome 88.0.4324.96

    - name: e2e
      id: e2e
      run: npx ng e2e --no-webdriver-update
    
    needs: environment-build

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Build and Deploy
      id: Ngh
      uses: JamesIves/github-pages-deploy-action@master
      env:
       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       BRANCH: gh-pages
       FOLDER: dist/authorize-example
       BUILD_SCRIPT: npx ng build --prod --base-href https://choutinghsiao.github.io/AuthorizeApp/

    - name: Notify
      id: Notify
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: ${{ format('{0} {1} n {2}', github.workflow,  job.status, 'https://choutinghsiao.github.io/AuthorizeApp/')}}
    
    needs: [Lint, test, e2e]
