name: AuthorizeApp GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: Checkout
      uses: actions/checkout@master

    - name: Use Node.js 12.8
      id: Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8

    - name: update chrome
      id: update
      run: sudo apt-get update && sudo apt-get upgrade google-chrome-stable -y

    - name: install
      id: install
      run: npm install

    - name: test
      id: test
      run: npm test

    - name: e2e
      id: e2e
      run: npm run e2e

    - name: Build and Deploy
      id: Ngh
      uses: JamesIves/github-pages-deploy-action@master
      env:
       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       BRANCH: gh-pages
       FOLDER: dist/authorize-example
       BUILD_SCRIPT: npx ng build --prod --base-href https://choutinghsiao.github.io/AuthorizeApp/

    - name: Notify
      id: Notify
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: ${{ format('{0} {1} n {2}', github.workflow,  job.status, 'https://choutinghsiao.github.io/AuthorizeApp/')}}
