name: AuthorizeApp GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: Checkout
      uses: actions/checkout@master
    - run: echo "ok"

    - name: Notify
      id: Notify
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: ${{ toJson(steps) }}
